FROM ubuntu:18.04

ENV TOKENIZERS_PARALLELISM=true

RUN apt-get update && apt-get install -y software-properties-common && add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && apt-get install -y python3.6 python3.6-dev python3-pip

RUN ln -sfn /usr/bin/python3.6 /usr/bin/python3 && ln -sfn /usr/bin/python3 /usr/bin/python && ln -sfn /usr/bin/pip3 /usr/bin/pip

RUN pip install torch==1.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html && rm -rf /root/.cache/pip

ENV LANG=C.UTF-8 \
  LANGUAGE=C.UTF-8 \
  LC_ALL=C.UTF-8

RUN mkdir /input_files/
RUN mkdir /output_files/

WORKDIR /app
COPY . /app
RUN pip install -r requirements_p36.txt

# Expose the port the app runs on
EXPOSE 8000

# Set a default port
ENV PORT=8000

# Get the huggingface token from the build args
ARG HF_TOKEN

# Make dirs
RUN mkdir -p /app/src/sdg/model_checkpoints/

# Install wget
RUN apt-get update && apt-get install -y wget build-essential

# Download model checkpoint
RUN wget --header="Authorization: Bearer ${HF_TOKEN}" https://huggingface.co/iNoBo/scinobo-sdg-classification-bert-topic/resolve/main/bert_topic_model_sdgs_no_num_of_topics?download=true -O /app/src/sdg/model_checkpoints/bert_topic_model_sdgs_no_num_of_topics

# Change working directory
WORKDIR /app/src

# Envs for uvicorn api
ENV HOST="0.0.0.0"
ENV LOG_PATH="sdg_api_models.log"
ENV GUIDED_THRES="0.4"
ENV BERT_THRES="0.7"
ENV BERT_THRES_OLD="0.95"
ENV BERT_ATT_THRES_OLD="0.98"
ENV BERTOPIC_SCORE_THRES="0.14"
ENV BERTOPIC_COUNT_THRES="1"

# Run a shell
CMD ["bash"]